### ISSUE TITLE
Hello, thank you for sharing this code on github. I would like to use your code to run the following training and test, but I have just been involved in deeplearning learning. Could you please share the specific operation steps

### ISSUE THREAD

**Issue by watchmexiang** [jerofad/Pothole-Crack-Detection_MRCNN#1]
Hello, thank you for sharing this code on github. I would like to use your code to run the following training and test, but I have just been involved in  deeplearning. Could you please share the specific operation steps

**Comment by jerofad** [comment]
Hi. 
Step 1 Clone the repo
git clone https://github.com/jerofad/Pothole-Crack-Detection_MRCNN

Step 2 Change direcrory to the new repo:
cd Pothole-Crack-Detection_MRCNN

Step 3 Download the pre-trained MRCNN model
wget https://github.com/matterport/Mask_RCNN/releases/download/v2.0/mask_rcnn_coco.h5

Step 4: Run the training on the dataset
python pot_crack.py train --dataset=datasets/pot-crack/ --weights=coco.

Goodluck. If you need any help please do contact.
